# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: XDAD_CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@main

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name:  Build docs
      run: |
        npm install && npm run docs:build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        ACCESS_TOKEN: ${{ secrets.XDAD_DEPLOY_KEY }}
        GITHUB_TOKEN: ${{ secrets.XDAD_DEPLOY_KEY }}
        BRANCH: doc-site
        FOLDER: docs-dist
        REPOSITORY_NAME: MUOU-HANG/muou-hang.github.io
        TARGET_FOLDER: /

      env:
        CI: true
